import Login from "@/app/components/Login";
import React from "react";
export const metadata = {
  title: "Login Page | CPET Online",
  description: "Generated by create next app",
};
function page() {
  return (
    <div>
      <Login />
    </div>
  );
}

export default page;
