import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import {UserProvider}from '@/app/utils/contexts/UserContext'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CPET Online",
  description: "CPET offers an inclusive online learning platform accessible to the public, including women. With a wide range of courses, it empowers individuals by providing flexible education opportunities and fostering a supportive community for personal and professional growth.Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + "w-full overflow-x-hidden antialiased"}>
        <UserProvider>
          <Header/>
        </UserProvider>
        {children}
        <Footer/>
      </body>
    </html>
  );

}
