import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import {UserProvider}from '@/app/utils/contexts/UserContext'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CPET Online",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Navbar />
        </UserProvider>
        {children}
      </body>
    </html>
  );
}
