import DeleteCourse from "@/app/components/DeleteCourse";
import React from "react";

export const metadata = {
  title: "Delete Course | CPET Online",
  description: "Generated by create next app",
};
function page() {
  return (
    <div>
      <DeleteCourse />
    </div>
  );
}

export default page;
