import Dashboard from "@/app/components/Dashboard";
// import Dashboard2 from "@/app/components/Dashboard2";

export const metadata = {
  title: "Dashboard | CPET Online",
  description: "Generated by create next app",
};
function page() {
  return <>
  {/* <Dashboard2 /> */}
  <Dashboard />
  </>;
}
export default page;
