import Dashboard from "@/app/components/Dashboard";

export const metadata = {
  title: "Dashboard | CPET Online",
  description: "Generated by create next app",
};
function page() {
  return <>
  <Dashboard />
  </>;
}
export default page;
