import EditCourse from "@/app/components/EditCourse";
import React from "react";

export const metadata = {
  title: "Edit Course | CPET Online",
  description: "Generated by create next app",
};
function page() {
  return (
    <div>
      <EditCourse />
    </div>
  );
}

export default page;
