import React from 'react'
import Register from '../components/Register'
export const metadata = {
    title: 'Create Account | CPET Online',
    description: 'Generated by create next app',
  }
function page() {
  return (
    <div>
        <Register/>
    </div>
  )
}

export default page